A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verification/', views.UserVerificationView.as_view(), name='user_verification'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout')
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_object/<key>/', views.DeleteBucketObject.as_view(), name='delete_object'),
    path('download_object/<key>/', views.DownloadBucketObject.as_view(), name='download_object')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path("detail/<int:order_id>/", views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='pay_order'),
    path('verify/', views.OrderVerifyView.as_view(), name='verify_order'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon')
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
    <p class="alert alert-{{ msg.tags }}">{{ msg  }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
        {% else %}
        <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
        <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
        {% endif %}
        {% if request.user.is_admin %}
        <a class="nav-link active" href="{% url 'home:bucket' %}">Bucket</a>
        <a class="nav-link active" href="{% url 'orders:cart' %}">Cart {{ cart|length }} </a>
        {% endif %}
    </div>
  </div>
</nav>